# Generated by Django 3.2.7 on 2021-09-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_marks_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='marks',
            new_name='subject',
        ),
    ]
